CREATE USER 'spring5'@'%' IDENTIFIED BY 'spring5';

CREATE DATABASE spring5fs character set=utf8;

GRANT ALL PRIVILEGES ON spring5fs.* TO 'spring5'@'%';

CREATE TABLE spring5fs.MEMBER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMAIL VARCHAR(255),
  PASSWORD VARCHAR(100),
  NAME VARCHAR(100),
  REGDATE DATETIME,
  UNIQUE KEY (EMAIL)
) ENGINE=InnoDB CHARACTER SET = utf8;

INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, REGDATE) VALUES ('madvirus@madvirus.net', '1234', 'cbk', now());